<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace geoipapi\geoipapi\Models\Operations;

use geoipapi\geoipapi\Utils\SpeakeasyMetadata;
class GetIpDataRequest
{
    /**
     *
     * @var ?string $ipAddress
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=ip_address')]
    public ?string $ipAddress = null;

    /**
     * @param  ?string  $ipAddress
     * @phpstan-pure
     */
    public function __construct(?string $ipAddress = null)
    {
        $this->ipAddress = $ipAddress;
    }
}