<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace geoipapi\geoipapi\Models\Components;


class CountryInfo
{
    /**
     *
     * @var ?bool $isEuMember
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_eu_member')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isEuMember = null;

    /**
     *
     * @var ?string $currencyCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $currencyCode = null;

    /**
     *
     * @var ?string $continent
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('continent')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $continent = null;

    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     *
     * @var ?string $countryCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $countryCode = null;

    /**
     *
     * @var ?string $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $state = null;

    /**
     *
     * @var ?string $city
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $city = null;

    /**
     *
     * @var ?string $zip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('zip')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $zip = null;

    /**
     *
     * @var ?string $timezone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timezone')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $timezone = null;

    /**
     * @param  ?bool  $isEuMember
     * @param  ?string  $currencyCode
     * @param  ?string  $continent
     * @param  ?string  $name
     * @param  ?string  $countryCode
     * @param  ?string  $state
     * @param  ?string  $city
     * @param  ?string  $zip
     * @param  ?string  $timezone
     * @phpstan-pure
     */
    public function __construct(?bool $isEuMember = null, ?string $currencyCode = null, ?string $continent = null, ?string $name = null, ?string $countryCode = null, ?string $state = null, ?string $city = null, ?string $zip = null, ?string $timezone = null)
    {
        $this->isEuMember = $isEuMember;
        $this->currencyCode = $currencyCode;
        $this->continent = $continent;
        $this->name = $name;
        $this->countryCode = $countryCode;
        $this->state = $state;
        $this->city = $city;
        $this->zip = $zip;
        $this->timezone = $timezone;
    }
}