<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace geoipapi\geoipapi\Models\Components;


class ErrorResponse
{
    /**
     *
     * @var string $ip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ip')]
    public string $ip;

    /**
     *
     * @var string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    public string $error;

    /**
     *
     * @var ?bool $success
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $success = null;

    /**
     * @param  string  $ip
     * @param  string  $error
     * @param  ?bool  $success
     * @phpstan-pure
     */
    public function __construct(string $ip, string $error, ?bool $success = false)
    {
        $this->ip = $ip;
        $this->error = $error;
        $this->success = $success;
    }
}