<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace geoipapi\geoipapi\Models\Components;


class GeoIPResponse
{
    /**
     *
     * @var string $ip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ip')]
    public string $ip;

    /**
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     *
     * @var CountryInfo $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
    #[\Speakeasy\Serializer\Annotation\Type('\geoipapi\geoipapi\Models\Components\CountryInfo')]
    public CountryInfo $country;

    /**
     *
     * @var LocationInfo $location
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('location')]
    #[\Speakeasy\Serializer\Annotation\Type('\geoipapi\geoipapi\Models\Components\LocationInfo')]
    public LocationInfo $location;

    /**
     *
     * @var AsnInfo $asn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('asn')]
    #[\Speakeasy\Serializer\Annotation\Type('\geoipapi\geoipapi\Models\Components\AsnInfo')]
    public AsnInfo $asn;

    /**
     * @param  string  $ip
     * @param  string  $type
     * @param  CountryInfo  $country
     * @param  LocationInfo  $location
     * @param  AsnInfo  $asn
     * @phpstan-pure
     */
    public function __construct(string $ip, string $type, CountryInfo $country, LocationInfo $location, AsnInfo $asn)
    {
        $this->ip = $ip;
        $this->type = $type;
        $this->country = $country;
        $this->location = $location;
        $this->asn = $asn;
    }
}