<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace geoipapi\geoipapi\Models\Components;


class LocationInfo
{
    /**
     *
     * @var ?float $latitude
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('latitude')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $latitude = null;

    /**
     *
     * @var ?float $longitude
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('longitude')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $longitude = null;

    /**
     * @param  ?float  $latitude
     * @param  ?float  $longitude
     * @phpstan-pure
     */
    public function __construct(?float $latitude = null, ?float $longitude = null)
    {
        $this->latitude = $latitude;
        $this->longitude = $longitude;
    }
}