<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace geoipapi\geoipapi;



/** GeoIp - GeoIPAPI.com - Enterprise IP Geolocation: A high-performance, enterprise-grade IP Geolocation API providing real-time data for personalization, analytics, and security. Supports JSON, JSONP, XML, and YAML formats. */
class GeoIp
{
    public const SERVERS = [
        'https://api.geoipapi.com',
    ];

    /**
     * Access IP geolocation data in various formats.
     *
     * @var GeoIPEndpoints $$geoIPEndpoints
     */
    public GeoIPEndpoints $geoIPEndpoints;

    /**
     * Returns a new instance of the SDK builder used to configure and create the SDK instance.
     *
     * @return GeoIpBuilder
     */
    public static function builder(): GeoIpBuilder
    {
        return new GeoIpBuilder();
    }

    /**
     * @param  SDKConfiguration  $sdkConfiguration
     */
    public function __construct(
        public SDKConfiguration $sdkConfiguration,
    ) {
        $this->geoIPEndpoints = new GeoIPEndpoints($this->sdkConfiguration);
        $this->initHooks();

    }

    private function initHooks(): void
    {
        $this->sdkConfiguration = $this->sdkConfiguration->hooks->sdkInit($this->sdkConfiguration);
    }
}